Add rtc peripheral
nickray/lpc55-hal pull request #26
Opened 2020-09-10 22:15 UTC by conorpp

Add RTC peripheral.  

```rust
let mut rtc = hal.rtc.enabled(&mut syscon, token_32k_fro);

loop {
    heprintln!("{:?}", rtc.uptime()).ok();
}
// 1s
// ..
// 2s
// ..
```

Right now this uses `core::time::Duration`, but let's do another PR replacing time related types with [embedded_time](https://docs.rs/embedded-time/0.10.0/embedded_time/)

2020-09-19 12:27 UTC, nickray requested changes
Thanks! Just this one question, then I'll merge. Agreed on postponing overhaul of time/duration/baud etc.

2020-09-19 12:27 UTC, nickray commented on src/peripherals/pmc.rs
> +impl_power_control!(crate::typestates::ClocksSupport32KhzFroToken, pden_fro32k);
Not sure I understand why the first argument isn't `raw::RTC`?

2020-09-19 21:40 UTC, conorpp commented on src/peripherals/pmc.rs
> +impl_power_control!(crate::typestates::ClocksSupport32KhzFroToken, pden_fro32k);
The RTC doesn't need a power on signal, and can choose between multiple clock inputs.  the fro32k is one of the options and needs to be powered on but doesn't have a register block.  My other thought was to just put the power on logic just in `clocks.rs` but thought I'd try this.

2020-09-28 11:04 UTC, nickray commented
Ah, got it now.

At some point, we should probably model these "tokens" as "peripherals" and unify with the "peripherals" as coming from the PAC.

I think using the PAC object as "the peripheral" is a left-over from the extension trait approach used in earlier HALs, we could have ZSTs that consume + wrap whatever's necessary, but allow such unification so a FRO 32k clock is treater similarly to say the RNG.

2020-09-28 11:04 UTC, merged