Lfs macros
nickray/lpc55-hal pull request #34
Opened 2020-11-20 16:44 UTC by conorpp

Usage:

```rust

// Define implementation(s)
littlefs2_filesystem!(PlainFilesystem: (constants::CONFIG_FILESYSTEM_BOUNDARY));
littlefs2_prince_filesystem!(PrinceFilesystem: (constants::CONFIG_FILESYSTEM_BOUNDARY));

// ... 

// instantiate
let filesystem = PrinceFilesystem::new(flash_gordon, prince);
let filesystem = PlainFilesystem::new(flash_gordon);

```

Redo of #33

2020-11-20 19:50 UTC, nickray requested changes

2020-11-20 19:50 UTC, nickray commented on src/peripherals/prince.rs
> +    }
Something like
```
pub fn write_encrypted<R>(&mut self, f: impl FnOnce(&mut Self) -> R) -> R {
  unsafe { self.enable_encrypted_write() };
  let result = f(self);
  self.disable_encrypted_write();
  result
}
```

2020-11-20 19:50 UTC, nickray commented on src/peripherals/prince.rs
> +    }
And then you can remove the encryption enable/disable from the public interface.

2020-11-20 19:50 UTC, nickray commented on src/drivers/flash.rs
> +                self.prince.disable_encrypted_write();
With `write_encrypted` from the following, and something similar for the region enable/disable (not sketched):
```
fn write(...) -> ... {
  // convince the borrow-checker
  let prince = &mut self.prince;
  let flash_gordon = &mut self.flash_gordon;

  self.write_encrypted(|_prince| {
    <....>::write(flash_gordon, Self::BASE_OFFSET + offset, data)
  })
  // kind of iffy, all of the result is swallowed?
  .map(|_| data.len())
  .map_err(|_| littlefs2::io::Error::Io)
}
```

2020-11-20 19:50 UTC, nickray commented on src/drivers/flash.rs
> +                // }
remove

2020-11-20 19:51 UTC, nickray commented on src/peripherals/prince.rs
> +    }
And maybe `f` doesn't need Self parameter at all, ever?

2020-11-20 19:53 UTC, nickray commented
for reference: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9f85a46fdde1749d158f96b411c33a31

2020-11-20 20:22 UTC, conorpp commented on src/drivers/flash.rs
> +                let flash: *const u8 = ($BASE_OFFSET + off) as *const u8;
Like replace $BASE_OFFSET with Self::BASE_OFFSET?

2020-11-20 20:26 UTC, conorpp commented on src/drivers/flash.rs
> +                self.prince.disable_encrypted_write();
Done for encrypted_write.  I don't think the HAL peripheral should have a similar method for for the region enable since that's more application specific whether prince should only be turned on temporarily or always-on/always-off.  Like if code is encrypted, it should always be on.  Whereas for encrypted_write, it's always the case it should only be for the flash write.

2020-11-27 10:25 UTC, nickray commented on src/drivers/flash.rs
> +                let flash: *const u8 = ($BASE_OFFSET + off) as *const u8;
yes

2020-11-27 10:27 UTC, nickray commented on src/drivers/flash.rs
> +                self.prince.disable_encrypted_write();
I agree that the raw methods should remain exposed to turn prince on/off for a region.
It would still be more readable and error-avoiding to offer also the closure approach, for the multiple places this driver and possible direct users indeed do want to wrap flash operations with enable/disable calls :)

2020-11-27 12:01 UTC, conorpp commented on src/drivers/flash.rs
> +                self.prince.disable_encrypted_write();
Added closure methods for region enable

2020-11-27 12:02 UTC, conorpp commented
@nickray All comments addressed 👍

2020-12-29 22:54 UTC, merged